language: rust
sudo: false

cache: cargo

os:
  - linux

rust:
  - nightly

env:
  - STYLE="true"
  - STYLE=""

install:
  - if [ -n "$STYLE" ]; then rustup component add clippy-preview; rustup component add rustfmt-preview; fi

matrix:
  fast_finish: true

script:
  - if [ -n "$STYLE" ]; then cargo clippy --all-targets; fi
  - if [ -n "$STYLE" ]; then cargo fmt -- --check; fi
  - if [ -z "$STYLE" ]; then cargo test; fi
  - if [ -z "$STYLE" ]; then cargo build --features "toml-fmt"; fi
  - if [ -z "$STYLE" ]; then cargo build --features "json-fmt"; fi
