language: rust
sudo: false

cache: cargo

os:
  - linux

rust:
  - nightly

env:
  - CLIPPY="true"
  - CLIPPY=""

install:
  - if [ -n "$CLIPPY" ]; then rustup component add clippy-preview; rustup component add rustfmt-preview; fi

matrix:
  fast_finish: true

script:
  - if [ -n "$CLIPPY" ]; then cargo clippy --all-targets; fi
  - if [ -n "$CLIPPY" ]; then cargo fmt -- --check; fi
  - if [ -z "$CLIPPY" ]; then cargo test; fi
